### ISSUE TITLE
ToDo: Add login session example with cookies

### ISSUE THREAD

**Issue by flosse** [seed-rs/seed#258]
**Update**: I'll hopefully add a full example soon :)

*Original question:*
Are there examples how to use `seed::fetch::Request`s with cookies?
On load I'd like to know if the user is already logged in (a special cookie exists).
And I want to attach the cookie to some of the restricted API request.

**Comment by MartinKavik** [comment]
I don't use cookies so I think that there isn't an example. Let me know if you run into any problems.

**Comment by flosse** [comment]
> I don't use cookies so I think that there isn't an example.

ok, I'll try to build an login example :)

> Let me know if you run into any problems.

Thank you!

**Comment by MartinKavik** [comment]
Is the login example still in your todo list? Otherwise I suggest to close it, because API is merged (https://github.com/David-OConnor/seed/pull/272).

**Comment by flosse** [comment]
> Is the login example still in your todo list?

yes it is :) I'll rename the issue title to be more precise.

**Comment by AlterionX** [comment]
@flosse Are you manipulating the cookies on the browser side for login? Since I don't think you should be, what with cross site scripting and friends. Personally, I set Http-Only and Secure (which the browser knows how to handle) so the biggest problem is getting user data and sending password/user information, which is now an issue in the server and not in seed outside of the request API. Not sure you should encourage using cookies for this purpose otherwise.

That said, an example using cookies would be nice!
