### ISSUE TITLE
Avoid Allocations by API Design

### ISSUE THREAD

**Issue by NeverGivinUp** [seed-rs/seed#419]
In my first scan of Seed, i noticed 
```
pub type WindowEventsFn<Ms, Mdl> = fn(&Mdl) -> Vec<EventHandler<Ms>>;
```
is a function that requires returning a `Vec`. 

I think (though I'm not certain) this function gets called on every event. That would be inefficient, as that requires an allocation on each event. Considering that moving the mouse or resizing the window creates a dense stream of events I suggest changing to 
```
pub type WindowEventsFn<Ms, Mdl> = fn(&Mdl, ) -> &'static [EventHandler<Ms>];
```
,where the vector backing the slice needs to be held as a mutable static and requires the function to use `unsafe`

or
```
pub type WindowEventsFn<Ms, Mdl> = fn(&Mdl, &mut Vec<EventHandler<Ms>>);
```
, where the vector is held by `App`.

Avoiding allocations might be a rather pervasive API design issue. (I'm just getting to know Seed, so I may be totally wrong about this and in that case, please forgive my premature nagging!) For instance, the View API allows/requires Vec and Map for returning multiple values. If these are allocated each time a view is rendered, those are many avoidable allocations.

**Comment by MartinKavik** [comment]
Ad `WindowEventsFn`
  - It has been replaced with the new API - https://github.com/seed-rs/seed/blob/master/examples/subscribe/src/lib.rs#L17 - `orders.stream` leaks the callback and `orders.stream_with_handle` will drop the callback. In both cases Seed doesn't have to recreate the handlers container on every event (as you rightly said). It will be documented with the new Seed 0.7.0 release (in weeks). 

Ad View API
  - Yes, `view` function has to return `Node<Msg` or `Vec<Node<Msg>>` (also these types can be "hidden" under `impl IntoNodes<Msg>`).
  - API `&model` -> `nodes` is inspired by proven Elm architecture. I assume that Elm is a little bit more suitable for it because of it's immutability and pure functions, but it doesn't change the fact that it's probably the simplest and therefore the best API from the user point of view. However we haven't explored the Rust ways how to optimize it properly yet - we are still focusing on the best public API, optimizations will come later - see e.g. https://github.com/seed-rs/seed/issues/385.
  - Also I think bigger problems than allocations are VDOM diffs, DOM modifications, etc. 
  - React-like hooks are on the way (we are waiting for stabilization of some Rust features) so it'll allow to apply other optimizations.

So.. the public API is the main priority and once stable we can optimize it. But don't be afraid to create an issue / topic on the forum / write on #devel on chat when you discover a way how to make API or internals better.

Cheers and thanks for the issue. Please close it if you think it's answered properly and you don't have any other questions.

**Comment by NeverGivinUp** [comment]
Thanks for the quick reply Martin :)

The way I understand in the 0.7 release you subscribe/unsubscribe a stream of events. That sounds like a very clean design 👍 

Regarding the View API, I agree that
* an ergonomic API should have higher priority than premature optimization
* there may be more speed gains to have in other parts -- and I trust you are a much better judge of that than I can ever be.

However performance is one of the main reasons we prefer Rust over Typescript or Elm, which are are very usable, more mature and have great libraries for many, many use cases. 

Some optimizations are possibly only if the API allows for them. And in this case I think the API will block optimization. Thus although I agree with you prioritizing API ergonomics over performance, I don't think they should be considered purely sequentially.

**Comment by MartinKavik** [comment]
> And in this case I think the API will block optimization.

When you have ideas for better API, feel free to create a new topic on the forum - even if we don't decide to implement it, it can affect are future development and thinking.

> I don't think ergonomics and performance should be considered purely sequentially.

I agree. 
Ergonomics has much bigger priority now because we still learn what works and what doesn't in real world projects - API should be stable in the near future, but still evolving pretty fast. So we don't want to dedicate too much time of our limited capacity to optimize something that we may remove in the future. We tries to apply best practices for performance as much as possible and we will use more sophisticated benchmark tools and optimizations later.

`view` is the special case - it's synchronized with the browser animation loop (i.e. Seed's runtime waits for next animation frame) and it's invoked almost only when we are handling `Msg` in `update`. Also we assume `view` functions don't contain any complex logic so it should be quite fast even with many allocations. As the result, users will notice some lags only when there are many thousands of nodes that are changing.
There aren't almost any optimizations yet, but Seed is still faster (according to a benchmark) than Yew and I didn't notice any lags while I was working on client apps. So there is a huge potential for performance improvement.
And we are waiting for more mature WebAssembly - all DOM calls have to go through "Javascript bridge" now - once we can call Browser API directly, it should be much faster.
