### ISSUE TITLE
Composing messages in (Sub-)views

### ISSUE THREAD

**Issue by sabine** [seed-rs/seed#456]
I've been looking at the tea_component example and tried to repeat that pattern for my own code.

I have a component with
```
Struct Msg {
    OnInput(String),
}
```

My component's view is declared as
```
fn view<Ms: 'static>(
    model: &Model,
    to_msg: impl FnOnce(Msg) -> Ms + Clone + 'static,
) -> impl IntoNodes<Ms>
```

Coming from Elm, the simplest solution to make this work with parameterized messages is to use the function composition operator like this to make a function of type `String -> Ms`:
```
input_ev(Ev::Input, to_msg << OnInput)
```
Here, `(a << b) c == a(b(c))`.

What is the most idiomatic thing to do in seed? (I am very inexperienced in Rust, so maybe the answer is obvious.)

From what I understand, the capability of writing reusable views also hinges on the facilities for composing messages of sub-views, so this question is not strictly about components, it's more about how to deal efficiently and conveniently with message hierarchies in general.

**Comment by sabine** [comment]
Hm ok, I should have looked deeper. The answer to this is in the Realworld example: 

https://github.com/seed-rs/seed-rs-realworld/blob/master/src/lib.rs#L282

The equivalent of Elm's `Html.map` exists and can be used, and it is called `map_msg`. Very nice. I got my code working.

**Comment by MartinKavik** [comment]
> The equivalent of Elm's Html.map exists and can be used, and it is called map_msg.

It's enough for the most cases but when you need to return component's and parent's messages from the one `view`, you cannot map everything with `map_msg`.
Example solution: https://github.com/seed-rs/seed/compare/master...MartinKavik:examples/demo_sub_views

I recommend to use rather [examples](https://github.com/seed-rs/seed/tree/master/examples) in this repo than RealWorld example for inspiration because they are always compilable and are used as integration tests for Seed. I'll update RealWorld once [Seeder](https://github.com/MartinKavik/seeder) is ready. Also [Webpack quickstart](https://github.com/seed-rs/seed-quickstart-webpack) has been recently updated and refactored.

[Example](https://github.com/seed-rs/seed/blob/master/examples/server_integration/client/src/lib.rs) that contains `map_msg`.

---

Let me know when you have other questions about Rust, Seed or Rust vs Elm (I've written some side-projects in Elm so I have an idea how it works). Ideally on forum or chat.
Cheers, M.

**Comment by sabine** [comment]
Thanks for the pointers. The sub views demo is very helpful (yes, I completely agree, having only `map_msg` would be cumbersome).

I'm generally very impressed that everything I came up with so far has already been covered in a reasonable fashion, or is planned to be covered eventually.
