### ISSUE TITLE
WebsocketMessage.bytes() doesn't work on Safari

### ISSUE THREAD

**Issue by tkubicz** [seed-rs/seed#470]
Hello,

`WebSocketMessage.bytes()` function doesn't work on safari and throws a runtime exception. This problem doesn't exist in Chrome or Firefox.

```
[Error] wasm-bindgen: imported JS function that was not marked as `catch` threw an error: – "getObject(arg0).arrayBuffer is not a function. (In 'getObject(arg0).arrayBuffer()', 'getObject(arg0).arrayBuffer' is undefined)↵↵Stack…"
	(anonymous function) (package.js:224)
	wasm-stub
	<?>.wasm-function[web_sys::features::gen_Blob::Blob::array_buffer::h6035f6f3793b884c]
	<?>.wasm-function[seed::browser::web_socket::message::WebSocketMessage::bytes::{{closure}}::h4555098a4d829d6b]
	<?>.wasm-function[<std::future::GenFuture<T> as core::future::future::Future>::poll::h15af837ff880ad89]
	<?>.wasm-function[std::future::poll_with_tls_context::hecb607a7f8c88198]
	<?>.wasm-function[client::chat::update::{{closure}}::h747c3fe65ead2501]
	<?>.wasm-function[<std::future::GenFuture<T> as core::future::future::Future>::poll::hc29e47b33fd89f21]
	<?>.wasm-function[<futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h2a1c1f0aec3006e2]
	<?>.wasm-function[<futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::h6dafe6092c28d87f]
	<?>.wasm-function[wasm_bindgen_futures::task::singlethread::Task::run::hd2ae8a7fce6033b4]
	<?>.wasm-function[wasm_bindgen_futures::queue::QueueState::run_all::h4f7092ed55373ca7]
	<?>.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::hb67de4d16789d1b1]
	<?>.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h727a037c3544a9ea]
	wasm-stub
	_dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h727a037c3544a9ea
	__wbg_adapter_31 (package.js:273:135)
	real (package.js:249)
	promiseReactionJob
```

Function `bytes()`(message.rs)  at line 52 uses `blob.array_buffer()` which is currently not supported by safari.
The quick fix for this issue would be to use `FileReader.readAsArrayBuffer`.

**Comment by MartinKavik** [comment]
Thanks for the report!

I tried to google a bit and it looks like an old bug because the most links that should prove that Safari doesn't support it, say that Safari already support it - see e.g. link on [SO](https://stackoverflow.com/questions/39129200/javascript-arraybuffer-slice-apparently-broken-in-safari-9-1-2).

- What's your Safari version? Is it the latest one?
- In the link above, there is one possible solution - could you try it and create a PR with it? Also a super simple unit test would be very nice because Seed should be tested also on Safari on CI (if not I can enable it).

Unfortunately I don't have Safari and it's pain to setup it on virtual machine and test it with multiple Safari versions... I would be very glad if you manage to do it.

Also please try [Response::bytes](https://github.com/seed-rs/seed/blob/dc230885218582ba70727b4842bd33ea6027c23f/src/browser/fetch/response.rs#L45) on your machine, too. I assume there would be the same problem.

**Comment by tkubicz** [comment]
Hi Martin,

* My safari is the newest one available: Version 13.1 (15609.1.20.111.8).
* Yeah, I can try to create a PR with fix for this issue.
* Response::bytes works just fine on the same version of Safari.

**Comment by MartinKavik** [comment]
Thank you very much!
Safari is [deactivated on CI](https://github.com/seed-rs/seed/blob/dc230885218582ba70727b4842bd33ea6027c23f/.github/workflows/main.yml#L43-L49) because of another bug.. So I will trust you that it works :)

**Comment by tkubicz** [comment]
Hi Martin,

Unfortunately the _simple_ fix from the link that you provided won't fix the issue. Simply `Blob.arrayBuffer` is not supported by many browsers including IE, Opera, Safari and some mobile browsers. Reference is [here](https://developer.mozilla.org/en-US/docs/Web/API/Blob/arrayBuffer).

I've created a PR to replace the usage with FileReader as I wrote in my first post. Feel free to take a look at it in your spare time.
