### ISSUE TITLE
[bug] brave browser is not loading newly created page view

### ISSUE THREAD

**Issue by eisenhaus335** [seed-rs/seed#490]
There is bug i found that brave is unable to load the new build wasm pkg and keep loading the old ones. I think there is some issue about their cache but not sure. This might need to mention brave browser team but i would like to create issue here first. The firefox browser does just fine tho in second attempt that you could see the "second placeholder"

Here is some screenshot:
![Screenshot from 2020-06-27 21-51-14](https://user-images.githubusercontent.com/25275731/85925246-51469300-b8c1-11ea-85d7-13e293fc2c97.png)
![Screenshot from 2020-06-27 21-50-06](https://user-images.githubusercontent.com/25275731/85925247-5277c000-b8c1-11ea-964a-c66ae38ecef9.png)
![Screenshot from 2020-06-27 21-45-53](https://user-images.githubusercontent.com/25275731/85925248-53105680-b8c1-11ea-8654-394eec091ee7.png)

https://github.com/eisenhaus335/application-seed

**Comment by MartinKavik** [comment]
I've just tried it on Windows. In the most cases it works as expected. There was one case where I have to click refresh button multiple times, however it sometimes happens also in Firefox or Chrome.

From my/Seed users experience, "exotic" browsers have often problems with WASM and JS modules because they integrate older cores than the mainstream browsers and there are still some bugs related to new features like WASM and modules even in the latest browser cores.

There is also missing a cache-busting mechanism in the basic Rust quickstart. If you want, you can create a PR with an implementation - the most popular is probably to append a random short string or content hash to wasm file name while a new version is building.

**Comment by arn-the-long-beard** [comment]
Hey. I use brave daily  to test my apps and I never got the issue on Seed.



> From my/Seed users experience, "exotic" browsers have often problems with WASM and JS modules because they integrate 
> older cores than the mainstream browsers and there are still some bugs related to new features like WASM and modules even 
> in the latest browser cores.

Interesting :stuck_out_tongue:  

Brave behavior from my user experience has always been same as Chrome (except for cookies and trackers and performance and good UI ) .

Did you make more tests @eisenhaus335  ? 

Do you think we could close the issue ?

**Comment by eisenhaus335** [comment]
This was long issue tho. Maybe brave somehow fix this issue with their magic update and cookies and such? 
I was using brave version at that time I make this issue. I will be take closer look later. And thank you to revisit this issue. This was like long time ago and I get chuckles someone revisit this

**Comment by arn-the-long-beard** [comment]
Hey, no prob bro

> btw I put nh** in brave browser just for chuckles. please never mind it

I do not understand what does it mean :stuck_out_tongue_closed_eyes:

**Comment by mankinskin** [comment]
I think this is because your browser is reusing it's files from cache, you can disable it. In firefox you can open developer tools > menu > settings > advanced settings > disable HTTP cache (when toolbox is open).
This will disable caching when developer toolbox is open.

**Comment by arn-the-long-beard** [comment]
Hey, no prob bro

> btw I put nh** in brave browser just for chuckles. please never mind it

I do not understand what do you mean there :smile:
