### ISSUE TITLE
How to handle websockets with sub-modules and mutliple update functions

### ISSUE THREAD

**Issue by FrankelJb** [seed-rs/seed#500]
Hello

I'm porting an old Elm app of mine to Seed and there a lot of similarities so I may be going down the wrong path based on those patterns. Its a SPA that is utilising websockets to connect to an actix backend. I want each page to handle its own websocket connection and thereby requires its own update.

My app is setup like this:

1. the main Seed app in `bin.rs` with an `enum Page` to handle the `url` paths (`enum Page {Home, Video(video_model), NotFound})`. The `fn Path::init(..)` coordinates the path to route between `/` and `/video/` etc. This is styled after the [pages example](https://github.com/seed-rs/seed/blob/master/examples/pages/README.md).
2. There is a `video` module to handle its own state. This is using the packaged `Websocket` client:

```
// video::Model
pub struct Model {
    populate_page: page::populate::Model,
    web_socket: WebSocket,
    web_socket_reconnector: StreamHandle,
}
```

Is this pattern of each sub-module having update (like Elm)? In Elm, I would map between the Msgs and I see there isn't a concensus on doing this in Seed. When calling

```
video::update<Ms: 'static>(msg: Msg, page: Page, orders: &mut impl Orders<Ms>)
```

from

```
bin::update(..) {
    ..
    Msg::VideoMsg(msg) => page::video::update(msg, model.page, orders), // error at model.page
    ..
}
```

I get the error:

```
cannot move out of `model.page` which is behind a mutable reference
move occurs because `model.page` has type `page::Page`, which does not implement the `Copy` trait
```

I can't just make the `video::Model` derive `Copy` and `Clone` because it has the websocket structs and they don't both implement Copy and Clone.

I'd really appreciate any guidance on how I could solve this, if I even should be.

**Comment by MartinKavik** [comment]
> In Elm, I would map between the Msgs

Many items (e.g. `Node`) has method `map_msg`. Example: https://github.com/seed-rs/seed/blob/867c679c6729a5c7f545a42720865d55fb1b1883/examples/server_integration/client/src/lib.rs#L75

---

`orders` doesn't have `map_msg` but it has `.proxy()` because it doesn't really map messages, only creates "bridges" between root `Msg` and submodule `Msg`s. Example: https://github.com/seed-rs/seed/blob/867c679c6729a5c7f545a42720865d55fb1b1883/examples/server_integration/client/src/lib.rs#L47

---

Or you can pass a callback/msg mapper from parent to child. Example: https://github.com/seed-rs/seed/blob/867c679c6729a5c7f545a42720865d55fb1b1883/examples/tea_component/src/lib.rs#L42 

---

So the patterns are Elm-like, you just want to use `orders.proxy` or `msg_map` for casting between `Msgs` and `orders.perform_cmd` instead of returning `Cmds` into Elm runtime. And `orders.subscribe` / `orders.notify` instead of `Sub` and `onUrlRequest` + `onUrlChange `. 

---

Back to your app.

One possible option would be replace:
```rust
Msg::VideoMsg(msg) => page::video::update(msg, model.page, orders)
````
with
```rust
Msg::VideoMsg(msg) => page::video::update(msg, &mut model.page, orders)  // and update `page::video::update` signature
```

Or perhaps you don't want to `match` `Page` variants in a submodule, so you can write something like:
```rust
Msg::VideoMsg(msg) => { 
    if let Page::Video(video_model) = &mut model.page {
        page::video::update(msg, video_model, orders)
    }
}
```
where `page::video::update` would have signature like `video::update<Ms: 'static>(msg: Msg, model: &Model, orders: &mut impl Orders<Ms>)` - `Model` is `page::video::Model`. That way the signature is consistent with the standard one and parent types don't have to "leak" to children.

Hope it helps!

**Comment by FrankelJb** [comment]
@MartinKavik, thanks for such an awesome response. Totally agree about not leaking the parent type.

I realised after I posted this that I need to use `&mut model.page` (or `Page::Video(ref mut video_model)`) and it compiled.

I'm faced with a new error now. The websocket connection fails to open when its contained in the video module. It throws a runtime expection: `panicked at 'WebSocket handler on_open can return only Msg, Option<Msg> or ()!'`. I tried to dig into it and found [this](https://github.com/seed-rs/seed/issues/391), but I'm not sure its related. The `video::Msg::WebsocketOpened` would return the enum `video::Msg`. Should it work to open websockets in submodules?

**Comment by MartinKavik** [comment]
> can return only Msg, Option<Msg> or ()!

I hope we will be able to rewrite it to a compile-time error soon, where the Rust compiler provides more context. In the most cases users try to use different `Msg` type - e.g. the parent's one instead of the submodule's `Msg`. So please make sure you are using the correct type - if everything looks good but still doesn't work, please post a link to your project / a snippet to [Gist](https://gist.github.com/) and I'll look at it. 

And I'll create a to-do issue that we should add some tips / detailed explanation to the panic message.

**Comment by FrankelJb** [comment]
Thanks again! It was related to the msg mapping. Closing as answered.
