### ISSUE TITLE
Update selected <option> in <select> element in view

### ISSUE THREAD

**Issue by 8176135** [seed-rs/seed#558]
How can I update which <option> is selected in a <select> element in view according to the value in the model? Just adding the `selected` attribute to the one that I want to select doesn't work once the user changes the value. 

Through javascript I would do something like `document.getElementById("select").selectedIndex = 0;`, but I'm not sure how I can do that through seed inside the view() function.

It seems something like the seek hooks might be useful here, but that requires nightly. Is there a way to do it on stable?

(it seems like github's markdown renderer broke)

**Comment by MartinKavik** [comment]
Notes:
- Seed Hooks doesn't require nightly since Rust 1.46. I've created an updated [repo](https://github.com/seed-rs/styles_hooks) with hooks, if you want to try it.
- it's generally painful to work with `select` (it's hard to style, browsers handle some events differently, etc.)

Back to the question.
Seed has a mechanism for direct (imperative) element access - `el_ref` + `ElRef`. See, for instance, [canvas example](https://github.com/seed-rs/seed/blob/master/examples/canvas/src/lib.rs) (or it's several times mentioned in [seed-rs.org](https://seed-rs.org/) tutorials). Then, you can call `selectedIndex` alternatives directly through `web_sys` crate.
However the simpler way should be just to add `At::Value` into `select` (but I can't find an example with `select` in Seed examples and I don't use it so I'm not sure how well it works now).
