### ISSUE TITLE
Encoding Relationship between Enum Variants of Model and Message in Type System

### ISSUE THREAD

**Issue by MarioIshac** [seed-rs/seed#594]
I came across this project yesterday in exploring Rust on the frontend, and have been working through the tutorials and example repositories. Been a great experience so far!

I'm taking a look at `seed-app-time-tracker` in this section of code: https://github.com/MartinKavik/seed-app-time-tracker/blob/master/src/lib.rs#L224-L245.

From my understanding, `Msg::ClientsAndProjectsMsg` is tied to `Page::ClientsAndProjects`. If the former is the selected variant of `Message`, then the latter should be the selected variant of `Model`. Yet, the example code linked has to do many `if let`s because `msg` and `model` are separate parameters to `update`, with this relationship not encoded in the type system. Theoretically, I could have a `Msg::TimeTrackerMsg` with a `Page::ClientsAndProjects`, and instead of that failing to build, it would do nothing at runtime since the `if let` doesn't match.

Is my understanding right? If so, is there anyway to encode that relationship, or is it impossible since `msg` and `model` are separate parameters to `update`?

**Comment by glennsl** [comment]
I think your understanding is correct.

But consider the scenario where you are on one page, start fetching something from the server, and then in the meantime switch to another page. How would you handle the server response when you're no longer on the page that requested it?

In order to ensure, at compile-time, that you cannot receive messages that are incompatible with the current state of the model you'd pretty much have to do everything in sequence. And that would make for a very unresponsive system.

**Comment by mankinskin** [comment]
The way I structure messages that are only meant for a single variant of my model is with nested message enums:
```rust
enum Page {
    Home(HomeModel),
    Article(ArticleModel),
}
enum PageMsg {
    Home(HomeMsg),
    Article(ArticleMsg),
}
enum ArticleMsg {
    ReceivedText(String),
}
enum HomeMsg {
    Login,
}
```
If you want to share message types across pages you can just wrap them in the page's message type
```rust
enum GeneralMessage {
    Notification(String),
}
enum ArticleMessage {
    ReceivedText(String),
    General(GeneralMessage),
}
```
then you can pass messages down your model in a pretty standard way:
```rust
fn update(model: &Page, msg: PageMsg, orders: &mut impl Orders<PageMsg>) {
    match model {
        Page::Home(model) => if let PageMsg::Home(msg) = msg {
            update(&model, msg, &mut orders.proxy(PageMsg::Home));
        },
        Page::Article(model) => if let PageMsg::Article(msg) = msg {
            update(&model, msg, &mut orders.proxy(PageMsg::Article));
        },
    }
}
```
You could probably make a macro for this pattern eventually..

**Comment by MartinKavik** [comment]
> ... with this relationship not encoded in the type system. Theoretically, I could have a Msg::TimeTrackerMsg with a Page::ClientsAndProjects, and instead of that failing to build, it would do nothing at runtime since the if let doesn't match.

I've published an [article](https://dev.to/martinkavik/moonzoon-dev-news-2-live-demo-zoon-examples-architectures-2oem) yesterday that compares architectures and talks also about that "relationship encoding" a bit.  The missing encoding is basically by design and it's a trade-off  for flexibility and simplicity. From my experience, I sometimes pass a wrong `Msg` type to `update` function however the compiler tells me it immediately and when you forget to call the `update` function, you find out it during the first test so it's not problem in practice.

@glennsl and @mankinskin already wrote excellent answers, so I'll just write a small tip:
I saw in some Elm apps a code like this:
```rust
fn update(msg: Msg, model: &mut Model, orders: &mut impl Orders<Msg>) {
    match (msg, &mut model.page) {
        (Msg::ClientsAndProjectsMsg(msg), Page::ClientsAndProjects(model)) => {
            page::clients_and_projects::update(msg, model, &mut orders.proxy(Msg::ClientsAndProjectsMsg))
        }
        (Msg::TimeTrackerMsg(msg), Page::TimeTracker(model)) => {
            page::time_tracker::update(msg, model, &mut orders.proxy(Msg::TimeTrackerMsg))
        },
        (_, _) => log!("Wrong Msg and Page combination!")
    }
}
```
It wasn't possible to write in Rust because of a combination of moved and referenced value in the `match` but there were some changes in recent Rust versions so maybe it's possible now. It's useful for debugging and when you want to handle `Msg`s that arrive too late from performed `Cmd`s when the user has already switched to an "incompatible" page.
```

**Comment by MarioIshac** [comment]
Alright thank you all for the answers, understand the tradeoff now. Will be going with matching on the tuple + the enum structures  mankinskin showed.
